using Newtonsoft.Json;
using NEXX_SAWLUZIntegration.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NEXX_SAWLUZIntegration.Models
{
    public class MarketingDocuments
    {
        public string odatacontext { get; set; }
        public string odataetag { get; set; }
        public int? DocEntry { get; set; }
        public int? DocNum { get; set; }
        public string DocType { get; set; }
        public string HandWritten { get; set; }
        public string Printed { get; set; }
        public string DocDate { get; set; }
        public string DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public object Address { get; set; }
        public object NumAtCard { get; set; }
        public double? DocTotal { get; set; }
        public object AttachmentEntry { get; set; }
        public string DocCurrency { get; set; }
        public double? DocRate { get; set; }
        public string Reference1 { get; set; }
        public object Reference2 { get; set; }
        public object Comments { get; set; }
        public string JournalMemo { get; set; }
        public int? PaymentGroupCode { get; set; }
        public string DocTime { get; set; }
        public int? SalesPersonCode { get; set; }
        public int? TransportationCode { get; set; }
        public string Confirmed { get; set; }
        public object ImportFileNum { get; set; }
        public string SummeryType { get; set; }
        public int? ContactPersonCode { get; set; }
        public string ShowSCN { get; set; }
        public int? Series { get; set; }
        public string TaxDate { get; set; }
        public string PartialSupply { get; set; }
        public string DocObjectCode { get; set; }
        public string ShipToCode { get; set; }
        public object Indicator { get; set; }
        public object FederalTaxID { get; set; }
        public double? DiscountPercent { get; set; }
        public object PaymentReference { get; set; }
        public string CreationDate { get; set; }
        public string UpdateDate { get; set; }
        public int? FinancialPeriod { get; set; }
        public int? UserSign { get; set; }
        public object TransNum { get; set; }
        public double? VatSum { get; set; }
        public double? VatSumSys { get; set; }
        public double? VatSumFc { get; set; }
        public string NetProcedure { get; set; }
        public double? DocTotalFc { get; set; }
        public double? DocTotalSys { get; set; }
        public object Form1099 { get; set; }
        public object Box1099 { get; set; }
        public string RevisionPo { get; set; }
        public string RequriedDate { get; set; }
        public string CancelDate { get; set; }
        public string BlockDunning { get; set; }
        public string Submitted { get; set; }
        public int? Segment { get; set; }
        public string PickStatus { get; set; }
        public string Pick { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentBlock { get; set; }
        public object PaymentBlockEntry { get; set; }
        public object CentralBankIndicator { get; set; }
        public string MaximumCashDiscount { get; set; }
        public string Reserve { get; set; }
        public object Project { get; set; }
        public object ExemptionValidityDateFrom { get; set; }
        public object ExemptionValidityDateTo { get; set; }
        public string WareHouseUpdateType { get; set; }
        public string Rounding { get; set; }
        public object ExternalCorrectedDocNum { get; set; }
        public object InternalCorrectedDocNum { get; set; }
        public object NextCorrectingDocument { get; set; }
        public string DeferredTax { get; set; }
        public object TaxExemptionLetterNum { get; set; }
        public double? WTApplied { get; set; }
        public double? WTAppliedFC { get; set; }
        public string BillOfExchangeReserved { get; set; }
        public object AgentCode { get; set; }
        public double? WTAppliedSC { get; set; }
        public double? TotalEqualizationTax { get; set; }
        public double? TotalEqualizationTaxFC { get; set; }
        public double? TotalEqualizationTaxSC { get; set; }
        public int? NumberOfInstallments { get; set; }
        public string ApplyTaxOnFirstInstallment { get; set; }
        public string TaxOnInstallments { get; set; }
        public double? WTNonSubjectAmount { get; set; }
        public double? WTNonSubjectAmountSC { get; set; }
        public double? WTNonSubjectAmountFC { get; set; }
        public double? WTExemptedAmount { get; set; }
        public double? WTExemptedAmountSC { get; set; }
        public double? WTExemptedAmountFC { get; set; }
        public double? BaseAmount { get; set; }
        public double? BaseAmountSC { get; set; }
        public double? BaseAmountFC { get; set; }
        public double? WTAmount { get; set; }
        public double? WTAmountSC { get; set; }
        public double? WTAmountFC { get; set; }
        public object VatDate { get; set; }
        public object DocumentsOwner { get; set; }
        public object FolioPrefixString { get; set; }
        public object FolioNumber { get; set; }
        public string DocumentSubType { get; set; }
        public object BPChannelCode { get; set; }
        public object BPChannelContact { get; set; }
        public string Address2 { get; set; }
        public string DocumentStatus { get; set; }
        public string PeriodIndicator { get; set; }
        public object PayToCode { get; set; }
        public object ManualNumber { get; set; }
        public string UseShpdGoodsAct { get; set; }
        public string IsPayToBank { get; set; }
        public object PayToBankCountry { get; set; }
        public object PayToBankCode { get; set; }
        public object PayToBankAccountNo { get; set; }
        public object PayToBankBranch { get; set; }
        public int? BPL_IDAssignedToInvoice { get; set; }
        public double? DownPayment { get; set; }
        public string ReserveInvoice { get; set; }
        public int? LanguageCode { get; set; }
        public object TrackingNumber { get; set; }
        public object PickRemark { get; set; }
        public object ClosingDate { get; set; }
        public object SequenceCode { get; set; }
        public object SequenceSerial { get; set; }
        public object SeriesString { get; set; }
        public object SubSeriesString { get; set; }
        public string SequenceModel { get; set; }
        public string UseCorrectionVATGroup { get; set; }
        public double? TotalDiscount { get; set; }
        public double? DownPaymentAmount { get; set; }
        public double? DownPaymentPercentage { get; set; }
        public string DownPaymentType { get; set; }
        public double? DownPaymentAmountSC { get; set; }
        public double? DownPaymentAmountFC { get; set; }
        public double? VatPercent { get; set; }
        public object ServiceGrossProfitPercent { get; set; }
        public object OpeningRemarks { get; set; }
        public object ClosingRemarks { get; set; }
        public double? RoundingDiffAmount { get; set; }
        public double? RoundingDiffAmountFC { get; set; }
        public double? RoundingDiffAmountSC { get; set; }
        public string Cancelled { get; set; }
        public object SignatureInputMessage { get; set; }
        public object SignatureDigest { get; set; }
        public object CertificationNumber { get; set; }
        public object PrivateKeyVersion { get; set; }
        public string ControlAccount { get; set; }
        public string InsuranceOperation347 { get; set; }
        public string ArchiveNonremovableSalesQuotation { get; set; }
        public object GTSChecker { get; set; }
        public object GTSPayee { get; set; }
        public int? ExtraMonth { get; set; }
        public int? ExtraDays { get; set; }
        public int? CashDiscountDateOffset { get; set; }
        public string StartFrom { get; set; }
        public string NTSApproved { get; set; }
        public object ETaxWebSite { get; set; }
        public object ETaxNumber { get; set; }
        public object NTSApprovedNumber { get; set; }
        public string EDocGenerationType { get; set; }
        public object EDocSeries { get; set; }
        public object EDocNum { get; set; }
        public object EDocExportFormat { get; set; }
        public string EDocStatus { get; set; }
        public object EDocErrorCode { get; set; }
        public object EDocErrorMessage { get; set; }
        public string DownPaymentStatus { get; set; }
        public object GroupSeries { get; set; }
        public object GroupNumber { get; set; }
        public string GroupHandWritten { get; set; }
        public object ReopenOriginalDocument { get; set; }
        public object ReopenManuallyClosedOrCanceledDocument { get; set; }
        public string CreateOnlineQuotation { get; set; }
        public object POSEquipmentNumber { get; set; }
        public object POSManufacturerSerialNumber { get; set; }
        public object POSCashierNumber { get; set; }
        public string ApplyCurrentVATRatesForDownPaymentsToDraw { get; set; }
        public string ClosingOption { get; set; }
        public object SpecifiedClosingDate { get; set; }
        public string OpenForLandedCosts { get; set; }
        public string AuthorizationStatus { get; set; }
        public double? TotalDiscountFC { get; set; }
        public double? TotalDiscountSC { get; set; }
        public string RelevantToGTS { get; set; }
        public string BPLName { get; set; }
        public string VATRegNum { get; set; }
        public object AnnualInvoiceDeclarationReference { get; set; }
        public object Supplier { get; set; }
        public object Releaser { get; set; }
        public object Receiver { get; set; }
        public object BlanketAgreementNumber { get; set; }
        public string IsAlteration { get; set; }
        public string CancelStatus { get; set; }
        public object AssetValueDate { get; set; }
        public string DocumentDelivery { get; set; }
        public object AuthorizationCode { get; set; }
        public object StartDeliveryDate { get; set; }
        public object StartDeliveryTime { get; set; }
        public object EndDeliveryDate { get; set; }
        public object EndDeliveryTime { get; set; }
        public object VehiclePlate { get; set; }
        public object ATDocumentType { get; set; }
        public object ElecCommStatus { get; set; }
        public object ElecCommMessage { get; set; }
        public string ReuseDocumentNum { get; set; }
        public string ReuseNotaFiscalNum { get; set; }
        public string PrintSEPADirect { get; set; }
        public object FiscalDocNum { get; set; }
        public object POSDailySummaryNo { get; set; }
        public object POSReceiptNo { get; set; }
        public object PointOfIssueCode { get; set; }
        public object Letter { get; set; }
        public object FolioNumberFrom { get; set; }
        public object FolioNumberTo { get; set; }
        public string InterimType { get; set; }
        public int? RelatedType { get; set; }
        public object RelatedEntry { get; set; }
        public object SAPPassport { get; set; }
        public object DocumentTaxID { get; set; }
        public object DateOfReportingControlStatementVAT { get; set; }
        public object ReportingSectionControlStatementVAT { get; set; }
        public string ExcludeFromTaxReportControlStatementVAT { get; set; }
        public object POS_CashRegister { get; set; }
        public string UpdateTime { get; set; }
        public object CreateQRCodeFrom { get; set; }
        public object PriceMode { get; set; }
        public string ShipFrom { get; set; }
        public string CommissionTrade { get; set; }
        public string CommissionTradeReturn { get; set; }
        public string UseBillToAddrToDetermineTax { get; set; }
        public object Cig { get; set; }
        public object Cup { get; set; }
        public object FatherCard { get; set; }
        public string FatherType { get; set; }
        public string ShipState { get; set; }
        public object ShipPlace { get; set; }
        public object CustOffice { get; set; }
        public object FCI { get; set; }
        public object AddLegIn { get; set; }
        public object LegTextF { get; set; }
        public object DANFELgTxt { get; set; }
        public string IndFinal { get; set; }
        public int? DataVersion { get; set; }
        public object LastPageFolioNumber { get; set; }
        public string InventoryStatus { get; set; }
        public string PlasticPackagingTaxRelevant { get; set; }
        public string NotRelevantForMonthlyInvoice { get; set; }
        public object U_B1SYS_ConnTypeCode { get; set; }
        public object U_B1SYS_TensGrpCode { get; set; }
        public object U_B1SYS_EnergConsCls { get; set; }
        public object U_B1SYS_ParticipantC { get; set; }
        public object U_B1SYS_SubscrCode { get; set; }
        public object U_B1SYS_MeterCode { get; set; }
        public object U_B1SYS_RevIndC510 { get; set; }
        public object U_B1SYS_RevIndD600 { get; set; }
        public object U_B1SYS_RevIndD510 { get; set; }
        public object U_B1SYS_FisDocStatus { get; set; }
        public object U_B1SYS_CargoTranTyp { get; set; }
        public object U_B1SYS_BpSenCNPJ { get; set; }
        public object U_B1SYS_BPSenIE { get; set; }
        public object U_B1SYS_BPSenCPF { get; set; }
        public object U_B1SYS_BPSenIBGE { get; set; }
        public object U_B1SYS_BpRecCNPJ { get; set; }
        public object U_B1SYS_BPRecIE { get; set; }
        public object U_B1SYS_BPRecCPF { get; set; }
        public object U_B1SYS_BPRecIBGE { get; set; }
        public object U_B1SYS_TaxID12 { get; set; }
        public int? U_B1SYS_ImportProc { get; set; }
        public object U_B1SYS_CNPJFromC { get; set; }
        public object U_B1SYS_StateOfTP { get; set; }
        public string U_ExportType { get; set; }
        public string U_ImportType { get; set; }
        public object U_SD_MotivoSf { get; set; }
        public object U_FCDirecta { get; set; }
        public string U_InvoiceGenerated { get; set; }
        public object U_NumInvoiceHeader { get; set; }
        public object U_StsApp { get; set; }
        public object U_ComDec { get; set; }
        public object U_CentroCusto { get; set; }
        public string U_Localidade { get; set; }
        public string U_FreInt { get; set; }
        public object U_VlrFreInt { get; set; }
        public object U_HCO_PesoBruto { get; set; }
        public object U_TaxaFin { get; set; }
        public string U_SD_PA { get; set; }
        public object U_HCO_DepOriDest { get; set; }
        public object U_SD_SUPERVISOR { get; set; }
        public string U_SF_ID { get; set; }
        public object U_SD_LOG_PA { get; set; }
        public object U_SD_ArquivoPA { get; set; }
        public string U_LOC1_Origin { get; set; }
        public object U_blockTest { get; set; }
        public object U_SD_REF_OTMEQP { get; set; }
        public object U_TmsEmbarque { get; set; }
        public object U_EOSS_Data_Prev_Fatur { get; set; }
        public object U_EOSS_CodigoPedidoMercanet { get; set; }
        public object U_IB_HCO_DEPINT { get; set; }
        public object U_IB_HCO_DEPEXT { get; set; }
        public object U_IB_HCO_DEPORI { get; set; }
        public object U_IB_HCO_DEPDES { get; set; }
        public object U_IB_HCO_MOVEST { get; set; }
        public string U_IG_Status_uMov { get; set; }
        public string U_IG_Status_Entrega { get; set; }
        public object U_IG_CodAgente_uMov { get; set; }
        public object U_IG_Status_Callback { get; set; }
        public object U_SerialNFe { get; set; }
        public object U_ReservaFast { get; set; }
        public string U_OrderDepartment { get; set; }
        public object U_SD_CodeReserva { get; set; }
        public object U_ModelAprov { get; set; }
        public string U_SD_Ativo { get; set; }
        public object[] Document_ApprovalRequests { get; set; }
        public List<Documentline> DocumentLines { get; set; }
        public object[] ElectronicProtocols { get; set; }
        public object[] WithholdingTaxDataWTXCollection { get; set; }
        public object[] WithholdingTaxDataCollection { get; set; }
        public object[] DocumentSpecialLines { get; set; }
        public Taxextension TaxExtension { get; set; }
        public object[] DocumentReferences { get; set; }

        public class Documentline
        {
            public int? LineNum { get; set; }
            public string ItemCode { get; set; }
            public string ItemDescription { get; set; }
            public double? Quantity { get; set; }
            public string ShipDate { get; set; }
            public double? Price { get; set; }
            public double? PriceAfterVAT { get; set; }
            public string Currency { get; set; }
            public double? Rate { get; set; }
            public double? DiscountPercent { get; set; }
            public string VendorNum { get; set; }
            public object SerialNum { get; set; }
            public string WarehouseCode { get; set; }
            public int? SalesPersonCode { get; set; }
            public double? CommisionPercent { get; set; }
            public string TreeType { get; set; }
            public string AccountCode { get; set; }
            public string UseBaseUnits { get; set; }
            public string SupplierCatNum { get; set; }
            public object CostingCode { get; set; }
            public string ProjectCode { get; set; }
            public object BarCode { get; set; }
            public string VatGroup { get; set; }
            public double? Height1 { get; set; }
            public object Hight1Unit { get; set; }
            public double? Height2 { get; set; }
            public object Height2Unit { get; set; }
            public double? Lengh1 { get; set; }
            public object Lengh1Unit { get; set; }
            public double? Lengh2 { get; set; }
            public object Lengh2Unit { get; set; }
            public double? Weight1 { get; set; }
            public int? Weight1Unit { get; set; }
            public double? Weight2 { get; set; }
            public object Weight2Unit { get; set; }
            public double? Factor1 { get; set; }
            public double? Factor2 { get; set; }
            public double? Factor3 { get; set; }
            public double? Factor4 { get; set; }
            public int? BaseType { get; set; }
            public object BaseEntry { get; set; }
            public object BaseLine { get; set; }
            public double? Volume { get; set; }
            public int? VolumeUnit { get; set; }
            public double? Width1 { get; set; }
            public object Width1Unit { get; set; }
            public double? Width2 { get; set; }
            public object Width2Unit { get; set; }
            public string Address { get; set; }
            public string TaxCode { get; set; }
            public string TaxType { get; set; }
            public string TaxLiable { get; set; }
            public string PickStatus { get; set; }
            public double? PickQuantity { get; set; }
            public object PickListIdNumber { get; set; }
            public object OriginalItem { get; set; }
            public string BackOrder { get; set; }
            public string FreeText { get; set; }
            public int? ShippingMethod { get; set; }
            public object POTargetNum { get; set; }
            public string POTargetEntry { get; set; }
            public object POTargetRowNum { get; set; }
            public string CorrectionInvoiceItem { get; set; }
            public double? CorrInvAmountToStock { get; set; }
            public double? CorrInvAmountToDiffAcct { get; set; }
            public double? AppliedTax { get; set; }
            public double? AppliedTaxFC { get; set; }
            public double? AppliedTaxSC { get; set; }
            public string WTLiable { get; set; }
            public string DeferredTax { get; set; }
            public double? EqualizationTaxPercent { get; set; }
            public double? TotalEqualizationTax { get; set; }
            public double? TotalEqualizationTaxFC { get; set; }
            public double? TotalEqualizationTaxSC { get; set; }
            public double? NetTaxAmount { get; set; }
            public double? NetTaxAmountFC { get; set; }
            public double? NetTaxAmountSC { get; set; }
            public object MeasureUnit { get; set; }
            public double? UnitsOfMeasurment { get; set; }
            public double? LineTotal { get; set; }
            public double? TaxPercentagePerRow { get; set; }
            public double? TaxTotal { get; set; }
            public string ConsumerSalesForecast { get; set; }
            public double? ExciseAmount { get; set; }
            public double? TaxPerUnit { get; set; }
            public double? TotalInclTax { get; set; }
            public object CountryOrg { get; set; }
            public string SWW { get; set; }
            public object TransactionType { get; set; }
            public string DistributeExpense { get; set; }
            public double? RowTotalFC { get; set; }
            public double? RowTotalSC { get; set; }
            public double? LastBuyInmPrice { get; set; }
            public double? LastBuyDistributeSumFc { get; set; }
            public double? LastBuyDistributeSumSc { get; set; }
            public double? LastBuyDistributeSum { get; set; }
            public double? StockDistributesumForeign { get; set; }
            public double? StockDistributesumSystem { get; set; }
            public double? StockDistributesum { get; set; }
            public double? StockInmPrice { get; set; }
            public string PickStatusEx { get; set; }
            public double? TaxBeforeDPM { get; set; }
            public double? TaxBeforeDPMFC { get; set; }
            public double? TaxBeforeDPMSC { get; set; }
            public object CFOPCode { get; set; }
            public object CSTCode { get; set; }
            public int? Usage { get; set; }
            public string TaxOnly { get; set; }
            public int? VisualOrder { get; set; }
            public double? BaseOpenQuantity { get; set; }
            public double? UnitPrice { get; set; }
            public string LineStatus { get; set; }
            public double? PackageQuantity { get; set; }
            public string Text { get; set; }
            public string LineType { get; set; }
            public object COGSCostingCode { get; set; }
            public string COGSAccountCode { get; set; }
            public string ChangeAssemlyBoMWarehouse { get; set; }
            public double? GrossBuyPrice { get; set; }
            public int? GrossBase { get; set; }
            public double? GrossProfitTotalBasePrice { get; set; }
            public object CostingCode2 { get; set; }
            public object CostingCode3 { get; set; }
            public object CostingCode4 { get; set; }
            public object CostingCode5 { get; set; }
            public object ItemDetails { get; set; }
            public object LocationCode { get; set; }
            public object ActualDeliveryDate { get; set; }
            public double? RemainingOpenQuantity { get; set; }
            public double? OpenAmount { get; set; }
            public double? OpenAmountFC { get; set; }
            public double? OpenAmountSC { get; set; }
            public object ExLineNo { get; set; }
            public object RequiredDate { get; set; }
            public double? RequiredQuantity { get; set; }
            public object COGSCostingCode2 { get; set; }
            public object COGSCostingCode3 { get; set; }
            public object COGSCostingCode4 { get; set; }
            public object COGSCostingCode5 { get; set; }
            public object CSTforIPI { get; set; }
            public object CSTforPIS { get; set; }
            public object CSTforCOFINS { get; set; }
            public object CreditOriginCode { get; set; }
            public string WithoutInventoryMovement { get; set; }
            public object AgreementNo { get; set; }
            public object AgreementRowNumber { get; set; }
            public object ActualBaseEntry { get; set; }
            public object ActualBaseLine { get; set; }
            public int? DocEntry { get; set; }
            public double? Surpluses { get; set; }
            public double? DefectAndBreakup { get; set; }
            public double? Shortages { get; set; }
            public string ConsiderQuantity { get; set; }
            public string PartialRetirement { get; set; }
            public double? RetirementQuantity { get; set; }
            public double? RetirementAPC { get; set; }
            public string ThirdParty { get; set; }
            public object PoNum { get; set; }
            public object PoItmNum { get; set; }
            public object ExpenseType { get; set; }
            public object ReceiptNumber { get; set; }
            public object ExpenseOperationType { get; set; }
            public object FederalTaxID { get; set; }
            public double? GrossProfit { get; set; }
            public double? GrossProfitFC { get; set; }
            public double? GrossProfitSC { get; set; }
            public string PriceSource { get; set; }
            public object StgSeqNum { get; set; }
            public object StgEntry { get; set; }
            public object StgDesc { get; set; }
            public int? UoMEntry { get; set; }
            public string UoMCode { get; set; }
            public double? InventoryQuantity { get; set; }
            public double? RemainingOpenInventoryQuantity { get; set; }
            public object ParentLineNum { get; set; }
            public int? Incoterms { get; set; }
            public int? TransportMode { get; set; }
            public object NatureOfTransaction { get; set; }
            public object DestinationCountryForImport { get; set; }
            public object DestinationRegionForImport { get; set; }
            public object OriginCountryForExport { get; set; }
            public object OriginRegionForExport { get; set; }
            public string ItemType { get; set; }
            public string ChangeInventoryQuantityIndependently { get; set; }
            public string FreeOfChargeBP { get; set; }
            public object SACEntry { get; set; }
            public object HSNEntry { get; set; }
            public double? GrossPrice { get; set; }
            public double? GrossTotal { get; set; }
            public double? GrossTotalFC { get; set; }
            public double? GrossTotalSC { get; set; }
            public int? NCMCode { get; set; }
            public object NVECode { get; set; }
            public string IndEscala { get; set; }
            public double? CtrSealQty { get; set; }
            public object CNJPMan { get; set; }
            public object CESTCode { get; set; }
            public object UFFiscalBenefitCode { get; set; }
            public string ReverseCharge { get; set; }
            public string ShipToCode { get; set; }
            public string ShipToDescription { get; set; }
            public object OwnerCode { get; set; }
            public double? ExternalCalcTaxRate { get; set; }
            public double? ExternalCalcTaxAmount { get; set; }
            public double? ExternalCalcTaxAmountFC { get; set; }
            public double? ExternalCalcTaxAmountSC { get; set; }
            public object StandardItemIdentification { get; set; }
            public object CommodityClassification { get; set; }
            public double? WeightOfRecycledPlastic { get; set; }
            public object PlasticPackageExemptionReason { get; set; }
            public object LegalText { get; set; }
            public object Cig { get; set; }
            public object Cup { get; set; }
            public object UnencumberedReason { get; set; }
            public string CUSplit { get; set; }
            public object ListNum { get; set; }
            public object RecognizedTaxCode { get; set; }
            public double? U_B1SYS_IVAST { get; set; }
            public object U_B1SYS_TaxUoM { get; set; }
            public double? U_B1SYS_QtyPerTaxUoM { get; set; }
            public string U_B1SYS_RevenueInd { get; set; }
            public string U_B1SYS_RevenueInd2 { get; set; }
            public object U_B1SYS_RevenueRec { get; set; }
            public object U_B1SYS_POSTotICMS { get; set; }
            public object U_B1SYS_PSTotISSQN { get; set; }
            public object U_B1SYS_PTotICMSST { get; set; }
            public object U_B1SYS_CodigoDePar { get; set; }
            public object U_B1SYS_IPIStmpCnt { get; set; }
            public object U_CommoditiesUsage { get; set; }
            public double? U_QtyUsedInvoice { get; set; }
            public double? U_InvAvailableQty { get; set; }
            public object U_NewVariant { get; set; }
            public object U_SpecialOBS { get; set; }
            public object U_OrderPriority { get; set; }
            public object U_Engineer { get; set; }
            public object U_SD_COM_VEND { get; set; }
            public object U_SD_COM_SUP { get; set; }
            public string U_SF_ID { get; set; }
            public object U_SX_CONFINS { get; set; }
            public object U_SDR_CC_CLIENTE { get; set; }
            public object U_HCO_TransLote { get; set; }
            public object U_SD_CodEtiqueta { get; set; }
            public string U_SD_NContrato { get; set; }
            public object U_SD_ItemLOC1 { get; set; }
            public object U_SD_DescItemLOC1 { get; set; }
            public object U_SD_NSerie { get; set; }
            public object U_SD_PerApuracao { get; set; }
            public object U_SD_Permanencia { get; set; }
            public object U_SD_ValorOriginal { get; set; }
            public object U_SD_ValorPagarPeriodo { get; set; }
            public object U_SD_DescontoAplicado { get; set; }
            public object U_SD_PercDesconto { get; set; }
            public object U_SD_Obs { get; set; }
            public object U_LOC1_Details { get; set; }
            public object U_SD_NumEtiqIn { get; set; }
            public object U_SD_NumEtiqFim { get; set; }
            public object U_SD_NumEtiqueta { get; set; }
            public string U_SD_Etiqueta { get; set; }
            public string U_sd_spf { get; set; }
            public object U_AX_QtdEtiqueta { get; set; }
            public object U_AX_QtdRefugo { get; set; }
            public object U_AX_MotRefugo { get; set; }
            public object U_SD_Kit { get; set; }
            public object U_AX_EntrInicio { get; set; }
            public object U_AX_HrInicio { get; set; }
            public object U_AX_EntrFim { get; set; }
            public object U_AX_HrFim { get; set; }
            public object[] LineTaxJurisdictions { get; set; }
            public object[] DocumentLineAdditionalExpenses { get; set; }
            public object[] WithholdingTaxLines { get; set; }
            public object[] SerialNumbers { get; set; }
            public object[] BatchNumbers { get; set; }
            public object[] DocumentLinesBinAllocations { get; set; }
        }
        
        public class Taxextension
        {
            public string TaxId0 { get; set; }
            public object TaxId1 { get; set; }
            public object TaxId2 { get; set; }
            public object TaxId3 { get; set; }
            public string TaxId4 { get; set; }
            public object TaxId5 { get; set; }
            public object TaxId6 { get; set; }
            public object TaxId7 { get; set; }
            public object TaxId8 { get; set; }
            public object TaxId9 { get; set; }
            public string State { get; set; }
            public string County { get; set; }
            public object Incoterms { get; set; }
            public object Vehicle { get; set; }
            public object VehicleState { get; set; }
            public object NFRef { get; set; }
            public object Carrier { get; set; }
            public object PackQuantity { get; set; }
            public object PackDescription { get; set; }
            public object Brand { get; set; }
            public object ShipUnitNo { get; set; }
            public double? NetWeight { get; set; }
            public double? GrossWeight { get; set; }
            public string StreetS { get; set; }
            public string BlockS { get; set; }
            public string BuildingS { get; set; }
            public string CityS { get; set; }
            public string ZipCodeS { get; set; }
            public string CountyS { get; set; }
            public string StateS { get; set; }
            public string CountryS { get; set; }
            public object StreetB { get; set; }
            public object BlockB { get; set; }
            public object BuildingB { get; set; }
            public object CityB { get; set; }
            public object ZipCodeB { get; set; }
            public object CountyB { get; set; }
            public object StateB { get; set; }
            public object CountryB { get; set; }
            public object ImportOrExport { get; set; }
            public object MainUsage { get; set; }
            public string GlobalLocationNumberS { get; set; }
            public object GlobalLocationNumberB { get; set; }
            public string TaxId12 { get; set; }
            public object TaxId13 { get; set; }
            public object BillOfEntryNo { get; set; }
            public object BillOfEntryDate { get; set; }
            public object OriginalBillOfEntryNo { get; set; }
            public object OriginalBillOfEntryDate { get; set; }
            public string ImportOrExportType { get; set; }
            public object PortCode { get; set; }
            public int? DocEntry { get; set; }
            public double? BoEValue { get; set; }
            public object ClaimRefund { get; set; }
            public object DifferentialOfTaxRate { get; set; }
            public object IsIGSTAccount { get; set; }
            public object TaxId14 { get; set; }
        }
    }
}
